[package]
name = "fishpond_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bevy = ["bevy_ecs"]

[dependencies]
shakmaty = "0.26.0"
bevy_ecs = { version = "0.13", optional = true }
